---
# fs tasks file for aervits.cockroachdb

- name: Mount a device for CockroachDB data
  mount:
    path: /data
    src: /dev/cockroachdb/data
    fstype: ext4
    opts: defaults,nofail,noatime,discard
    passno: '2'
    state: present

- name: Create an ext4 filesystem for CockroachDB data
  filesystem:
    fstype: ext4
    dev: /dev/cockroachdb/data
    opts: nodiscard

- name: Change file ownership, group and permissions for /data volume
  file:
    path: /data
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0700'
  with_items: "{{ cockroach_user }}"
