---
# user tasks file for aervits.cockroachdb

- name: Add cockroach service user {{ cockroach_user }}
  user:
    name: "{{ item }}"
    comment: "{{ item }} service account user"
  with_items: "{{ cockroach_user }}"
