--- 
- hosts: all
  become: yes 
  tasks:
  - name: Ensure NTP (for time synchronization) is installed. 
    package: 
      name: ntp 
      state: present

  - name: Ensure NTP is running. 
    service: 
      name: ntpd 
      state: started
      enabled: yes