--- 
- hosts: all
  become: yes 
  tasks:
  - name: Create an ext4 filesystem for CockroachDB
    filesystem:
      fstype: ext4
      dev: /dev/cockroachdb/data
      opts: -cc

  - name: Mount up device by label
    mount:
      path: /data
      src: /dev/cockroachdb/data
      fstype: ext4
      opts: defaults,nofail,noatime,discard
      passno: '2'
      state: present