---
# vars file for aervits.cockroachdb


"binary_version": {
    "full": "cockroach-v21.2.4.linux-amd64",
    "major": 21,
    "minor": 2,
    "revision": 4,
    "version_string": "21.2.4",
    "rc": ""
}

binary_url: "https://binaries.cockroachdb.com/{{binary_version.full}}.tgz"
