---
# vars file for aervits.cockroachdb


"binary_version": {
    "full": "cockroach-v19.1.9.linux-amd64",
    "major": 19,
    "minor": 1,
    "revision": 9,
    "version_string": "19.1.9",
    "rc": ""
}

binary_url: "https://binaries.cockroachdb.com/{{binary_version.full}}.tgz"
